# Generated by Django 4.2.9 on 2024-01-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_musician_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='album',
        ),
    ]
